services:
  mysql:
    image: mysql:8
    container_name: yugioh-personalcard-db
    restart: always
    environment:
      MYSQL_DATABASE: yugioh-personalcard-db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./DB/conf/personal_cards.sql:/docker-entrypoint-initdb.d/personal_cards.sql

  backend:
    build: ./backend
    container_name: pctcd-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/yugioh-personalcard-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pw
    volumes:
      - ./Personal-Cloud-TCG-Card-Database/Data:/app/Data

volumes:
  db-data: